metadata_root: "./examples/field_optimizations/"
metadata_file_name: "calibration_metadata_all_heliostats.csv"
data_dir: "/workVERLEIHNIX/share/PAINT"
tower_file_name: "WRI1030197-tower-measurements.json"
scenarios_dir: "./examples/field_optimizations/scenarios"
measured_data_dir: "./examples/field_optimizations/measured_data"
results_dir: "./examples/field_optimizations/results"
plots_dir: "./examples/field_optimizations/plots"
data_for_stral_dir: "./examples/field_optimizations/data_for_stral"
minimum_number_of_measurements: 6
kinematic_reconstruction_image_type: "flux"
surface_reconstruction_image_type: "flux-centered"
excluded_heliostats_for_reconstruction: ["BE20", "AP14", "AG21"]
heliostats_for_plots:
  - "AK54"
  - "AM55"
  - "AM56"
random_seed: 7
device: "cuda"
surface_reconstruction_optimization_configuration:
  max_epoch: 2
  batch_size: 48
  batch_size_outer: 48
  number_of_surface_points: 50
  number_of_control_points: 6
  number_of_rays: 170
  nurbs_degree: 3
  sample_limit: 2
  initial_learning_rate: 1e-06
  scheduler: "cyclic"
  min_learning_rate: 1e-06
  max_learning_rate: 0.0001
  step_size_up: 122
  reduce_factor: 0.2
  patience: 3
  threshold: 0.001
  cooldown: 5
  gamma: 0.92
  energy_tolerance: 0.01
  rho_flux_integral: 1.0
  weight_smoothness: 0.00
  weight_ideal_surface: 0.10
kinematics_reconstruction_optimization_configuration:
  max_epoch: 2
  batch_size: 192
  sample_limit: 2
  number_of_rays: 10
  initial_learning_rate: 1e-07
  scheduler: "cyclic"
  min_learning_rate: 1e-06
  max_learning_rate: 0.0001
  step_size_up: 122
  reduce_factor: 0.2
  patience: 3
  threshold: 0.001
  cooldown: 5
  gamma: 0.92
aim_point_optimization_configuration:
  max_epoch: 2
  batch_size: 96
  number_of_rays: 4
  initial_learning_rate: 1e-03
  scheduler: "cyclic"
  min_learning_rate: 1e-06
  max_learning_rate: 0.0001
  step_size_up: 122
  reduce_factor: 0.2
  patience: 3
  threshold: 0.001
  cooldown: 5
  gamma: 0.92
  rho_flux_integral: 1.0
  rho_local_flux: 1.0
  rho_spillage: 1.0
  max_flux_density: 1000000 # W/m^2
basic_config:
  batch_size: 96
  number_of_rays: 4
  dni: 500
  baseline_incident_ray_direction: [0.411, 0.706, -0.576, 0.0]
  baseline_target_area: "receiver"
  #baseline_aim_point: [-0.3299, -0.5030, 55.4552,  1.0000]        # Focal spot extracted from measured flux
  baseline_aim_point: [-0.19720931, -0.03458419, 54.929, 1.0]    # Aim point from protocol 
heliostat_list_baseline:
  - "AG48"
  - "AG49"
  - "AG50"
  - "AG51"
  - "AG52"
  - "AG53"
  - "AG54"
  - "AG55"
  - "AG56"
  - "AG57"
  - "AG58"
  - "AH48"
  - "AH49"
  - "AH50"
  - "AH55"
  - "AH56"
  - "AH57"
  - "AH58"
  - "AI48"
  - "AI49"
  - "AI50"
  - "AI51"
  - "AI52"
  - "AI53"
  - "AI54"
  - "AI55"
  - "AI56"
  - "AI57"
  - "AI58"
  - "AI59"
  - "AI60"
  - "AI61"
  - "AJ49"
  - "AJ50"
  - "AJ51"
  - "AJ53"
  - "AJ54"
  - "AJ55"
  - "AJ56"
  - "AJ57"
  - "AJ58"
  - "AJ61"
  - "AJ62"
  - "AK48"
  - "AK49"
  - "AK50"
  - "AK51"
  - "AK52"
  - "AK53"
  - "AK54"
  - "AK55"
  - "AK56"
  - "AK58"
  - "AK59"
  - "AK60"
  - "AK61"
  - "AK62"
  - "AL48"
  - "AL49"
  - "AL51"
  - "AL53"
  - "AL56"
  - "AL58"
  - "AL59"
  - "AL60"
  - "AL61"
  - "AL62"
  - "AM48"
  - "AM49"
  - "AM50"
  - "AM51"
  - "AM52"
  - "AM53"
  - "AM54"
  - "AM55"
  - "AM56"
  - "AM57"
  - "AM58"
  - "AM59"
  - "AM60"
  - "AM62"
  - "AN48"
  - "AN49"
  - "AN50"
  - "AN51"
  - "AN52"
  - "AN53"
  - "AN54"
  - "AN55"
  - "AN56"
  - "AN57"
  - "AN58"
  - "AN59"
  - "AN60"
  - "AN61"
  - "AN62"
